name: qrl
channels:
  - weinbe58
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cudatoolkit=10.1.168
  - cudnn=7.6.0
  - cupti=10.1.168
  - cython=0.29.11
  - dill=0.3.0
  - gmp=6.1.2
  - gmpy2=2.0.8
  - google-pasta=0.1.7
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.8.0
  - libstdcxx-ng=9.1.0
  - markdown=3.1.1
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mpc=1.1.0
  - mpfr=4.0.1
  - ncurses=6.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1d
  - pandas=0.24.2
  - pip=19.1.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - quspin=0.3.2
  - qutip=4.3.1
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tk=8.6.8
  - wheel=0.33.4
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - backcall==0.1.0
    - bayesian-optimization==1.0.1
    - celluloid==0.2.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.1
    - cma==2.7.0
    - colorama==0.4.1
    - cycler==0.10.0
    - decorator==4.4.0
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.17.1
    - gast==0.2.2
    - grpcio==1.22.0
    - gym==0.14.0
    - idna==2.8
    - importlib-metadata==0.19
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - jedi==0.15.1
    - joblib==0.13.2
    - jsonschema==3.1.1
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - llvmlite==0.29.0
    - lz4==2.1.10
    - matplotlib==3.0.3
    - more-itertools==7.2.0
    - mpi4py==3.0.3
    - nevergrad==0.2.3
    - numba==0.44.1
    - opencv-python==4.1.1.26
    - packaging==19.1
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.2.1
    - pluggy==0.12.0
    - prompt-toolkit==2.0.10
    - protobuf==3.8.0
    - psutil==5.6.3
    - ptyprocess==0.6.0
    - py==1.8.0
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyqt5==5.13.2
    - pyqt5-sip==12.7.0
    - pyrsistent==0.15.4
    - pytest==5.0.1
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - ray==0.7.5
    - redis==3.3.6
    - requests==2.22.0
    - rope==0.14.0
    - scikit-learn==0.21.3
    - scipy==1.2.1
    - seaborn==0.9.0
    - tensorboard-logger==0.1.0
    - tensorflow-gpu==1.14.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - torch==1.0.1
    - torchvision==0.2.2
    - tornado==6.0.3
    - tqdm==4.19.9
    - traitlets==4.3.3
    - typing-extensions==3.7.4
    - urllib3==1.25.7
    - wcwidth==0.1.7
    - werkzeug==0.15.4
    - zipp==0.5.2


